import type { AnalysisFactors } from "@/lib/analysis"
import type { StartSitPlayerInput } from "@/lib/recommendations/types"

const baseFactors = (overrides: Partial<AnalysisFactors>): AnalysisFactors => ({
  historicalPerformance: 0.58,
  matchupDifficulty: 0.52,
  defensiveSchemeImpact: 0.5,
  coordinatorTendencies: 0.55,
  recentForm: 0.5,
  injuryImpact: 0.55,
  weatherImpact: 0.52,
  ...overrides,
})

export const sampleStartSitRoster: StartSitPlayerInput[] = [
  {
    id: "jefferson",
    name: "Justin Jefferson",
    position: "WR",
    team: "MIN",
    opponent: "vs DET",
    season: 2024,
    week: 15,
    baselineProjection: 20.1,
    lineupSlot: "starter",
    factors: baseFactors({ recentForm: 0.78, historicalPerformance: 0.82, matchupDifficulty: 0.68 }),
    history: [
      { week: 11, recommendation: "start", success: true, actualPoints: 23.4, opponent: "@CHI" },
      { week: 12, recommendation: "start", success: true, actualPoints: 26.1, opponent: "@GB" },
      { week: 13, recommendation: "start", success: false, actualPoints: 12.5, opponent: "@SF" },
    ],
  },
  {
    id: "aiyuk",
    name: "Brandon Aiyuk",
    position: "WR",
    team: "SF",
    opponent: "@ SEA",
    season: 2024,
    week: 15,
    baselineProjection: 16.8,
    lineupSlot: "starter",
    factors: baseFactors({ recentForm: 0.62, matchupDifficulty: 0.55, injuryImpact: 0.72 }),
    history: [
      { week: 11, recommendation: "start", success: true, actualPoints: 18.9, opponent: "@TB" },
      { week: 12, recommendation: "start", success: true, actualPoints: 20.3, opponent: "@SEA" },
    ],
  },
  {
    id: "puka",
    name: "Puka Nacua",
    position: "WR",
    team: "LAR",
    opponent: "vs WAS",
    season: 2024,
    week: 15,
    baselineProjection: 17.2,
    lineupSlot: "bench",
    factors: baseFactors({ recentForm: 0.75, matchupDifficulty: 0.7, coordinatorTendencies: 0.68 }),
    history: [
      { week: 10, recommendation: "start", success: true, actualPoints: 22.7, opponent: "@ARI" },
      { week: 11, recommendation: "sit", success: false, actualPoints: 19.4, opponent: "@BUF" },
      { week: 12, recommendation: "start", success: true, actualPoints: 18.8, opponent: "@NE" },
    ],
  },
  {
    id: "tankdell",
    name: "Tank Dell",
    position: "WR",
    team: "HOU",
    opponent: "vs TEN",
    season: 2024,
    week: 15,
    baselineProjection: 14.1,
    lineupSlot: "bench",
    factors: baseFactors({ recentForm: 0.68, matchupDifficulty: 0.61, injuryImpact: 0.48 }),
    history: [
      { week: 11, recommendation: "sit", success: true, actualPoints: 8.6, opponent: "@NYJ" },
      { week: 12, recommendation: "start", success: true, actualPoints: 16.9, opponent: "vs JAX" },
      { week: 13, recommendation: "sit", success: false, actualPoints: 15.1, opponent: "@DEN" },
    ],
  },
  {
    id: "bijan",
    name: "Bijan Robinson",
    position: "RB",
    team: "ATL",
    opponent: "@ CAR",
    season: 2024,
    week: 15,
    baselineProjection: 18.4,
    lineupSlot: "starter",
    factors: baseFactors({ recentForm: 0.66, matchupDifficulty: 0.62, coordinatorTendencies: 0.58 }),
    history: [
      { week: 10, recommendation: "start", success: true, actualPoints: 21.2, opponent: "vs NO" },
      { week: 12, recommendation: "start", success: false, actualPoints: 12.3, opponent: "@TB" },
    ],
  },
  {
    id: "jaylenwarren",
    name: "Jaylen Warren",
    position: "RB",
    team: "PIT",
    opponent: "@ CIN",
    season: 2024,
    week: 15,
    baselineProjection: 12.6,
    lineupSlot: "bench",
    factors: baseFactors({ recentForm: 0.7, matchupDifficulty: 0.65, injuryImpact: 0.6 }),
    history: [
      { week: 11, recommendation: "sit", success: true, actualPoints: 9.1, opponent: "@CLE" },
      { week: 12, recommendation: "start", success: true, actualPoints: 17.4, opponent: "vs CIN" },
      { week: 13, recommendation: "start", success: false, actualPoints: 10.2, opponent: "@BAL" },
    ],
  },
]
