import type { TradeAnalyzerInput } from "@/lib/trades/types"

const weeksRemaining = 17

export const sampleTradeInput: TradeAnalyzerInput = {
  season: 2024,
  week: 15,
  totalWeeks: weeksRemaining,
  teamA: {
    teamId: "team-a",
    teamName: "Bay Area Legends",
    manager: "Alex",
    currentRecord: { wins: 8, losses: 5 },
    playoffProbability: 0.72,
    playersSent: [
      {
        id: "justin-jefferson",
        name: "Justin Jefferson",
        position: "WR",
        team: "MIN",
        restOfSeasonProjection: 20.4,
        injuryRisk: 0.15,
        scheduleDifficulty: 0.65,
        byeWeeksRemaining: 0,
      },
      {
        id: "james-conner",
        name: "James Conner",
        position: "RB",
        team: "ARI",
        restOfSeasonProjection: 12.3,
        injuryRisk: 0.35,
        scheduleDifficulty: 0.58,
      },
    ],
    playersReceived: [
      {
        id: "amonra-st-brown",
        name: "Amon-Ra St. Brown",
        position: "WR",
        team: "DET",
        restOfSeasonProjection: 19.2,
        injuryRisk: 0.1,
        scheduleDifficulty: 0.7,
      },
      {
        id: "jahmyr-gibbs",
        name: "Jahmyr Gibbs",
        position: "RB",
        team: "DET",
        restOfSeasonProjection: 15.4,
        injuryRisk: 0.2,
        scheduleDifficulty: 0.62,
      },
    ],
  },
  teamB: {
    teamId: "team-b",
    teamName: "Pacifica Waves",
    manager: "Priya",
    currentRecord: { wins: 6, losses: 7 },
    playoffProbability: 0.38,
    playersSent: [
      {
        id: "amonra-st-brown",
        name: "Amon-Ra St. Brown",
        position: "WR",
        team: "DET",
        restOfSeasonProjection: 19.2,
        injuryRisk: 0.1,
        scheduleDifficulty: 0.7,
      },
      {
        id: "jahmyr-gibbs",
        name: "Jahmyr Gibbs",
        position: "RB",
        team: "DET",
        restOfSeasonProjection: 15.4,
        injuryRisk: 0.2,
        scheduleDifficulty: 0.62,
      },
    ],
    playersReceived: [
      {
        id: "justin-jefferson",
        name: "Justin Jefferson",
        position: "WR",
        team: "MIN",
        restOfSeasonProjection: 20.4,
        injuryRisk: 0.15,
        scheduleDifficulty: 0.65,
        byeWeeksRemaining: 0,
      },
      {
        id: "james-conner",
        name: "James Conner",
        position: "RB",
        team: "ARI",
        restOfSeasonProjection: 12.3,
        injuryRisk: 0.35,
        scheduleDifficulty: 0.58,
      },
      {
        id: "george-pickens",
        name: "George Pickens",
        position: "WR",
        team: "PIT",
        restOfSeasonProjection: 11.5,
        injuryRisk: 0.25,
        scheduleDifficulty: 0.6,
      },
    ],
  },
  leagueSettings: {
    scoringType: "PPR",
    rosterSpots: { QB: 1, RB: 2, WR: 3, FLEX: 2, TE: 1 },
    keeperLeague: false,
  },
}
